### ISSUE TITLE
cpu运行速度1.5FPS？

### ISSUE THREAD

**Issue by codylcs** [k-ggs/siamFCppwarp#1]
感谢您的开源代码，但cpu(i7-8700)运行时发现fps只有1.5，不知道为什么和您测试的速度差了那么多？可以给点意见吗？利用gpu加载您提供的模型会报错，无法推理，可以上传下GPU 模型吗？

**Comment by k-ggs** [comment]
# #这么低吗 😮
### 可能是你输入得到图像尺寸太大导致的。我是在i7 十代上测试的应该差距不大。。(⊙o⊙)

**Comment by codylcs** [comment]
我用的dubug版本，应该和这个也有关系

**Comment by k-ggs** [comment]
。。。。。。

**Comment by codylcs** [comment]
速度没问题，release版本速度挺快的
